---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ping-exporter
  namespace: pingmonitor
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: ping-exporter
  template:
    metadata:
      labels:
        name: ping-exporter
    spec:
      terminationGracePeriodSeconds: 0
      tolerations:
      - operator: "Exists"
      hostNetwork: true
      serviceAccountName: ping-exporter
      # priorityClassName: system-node-critical
      containers:
      - image: docker.io/renatoruis/ping-exporter
        name: ping-exporter
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: PROMETHEUS_TEXTFILE_DIR
            value:
             /tmp/ping-metrics/
          - name: PROMETHEUS_TEXTFILE_PREFIX
            value: ping-exporter_
        volumeMounts:
          - name: pingmetrics
            mountPath: /tmp/ping-metrics
          - name: kubeconfig-file
            mountPath: /kubeconfig-file
          - name: kubelet-conf
            mountPath: /var/lib/kubelet/
            
      volumes:
        - name: kubelet-conf
          hostPath:
            path: /var/lib/kubelet/
        - name: kubeconfig-file
          hostPath:
            path: /etc/kubernetes/
        - name: pingmetrics
          hostPath:
            path: /tmp/ping-metrics