{{ if .Values.namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ping-exporter
  namespace: {{ if .Values.namespace }}{{ .Values.namespace }}{{- else }}{{ "ping-exporter" }}{{- end }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ping-exporter
  namespace: {{ if .Values.namespace }}{{ .Values.namespace }}{{- else }}{{ "ping-exporter" }}{{- end }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-ping-exporter
  namespace: {{ if .Values.namespace }}{{ .Values.namespace }}{{- else }}{{ "ping-exporter" }}{{- end }}
subjects:
- kind: ServiceAccount
  name: ping-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ping-exporter