---
apiVersion: v1
kind: Namespace
metadata:
  name: pingmonitor
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ping-exporter
  namespace: pingmonitor
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ping-exporter
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-ping-exporter
subjects:
- kind: ServiceAccount
  name: ping-exporter
  namespace: pingmonitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ping-exporter